name: youbike_android
description: YouBike Android App Translation

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.0
  sliding_up_panel: ^2.0.0 # 引入專業底部面板套件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
